integration:
  hishtory:
    enabled: true
    managed: true
    version: "0.208"
    offline: true
    settings:
      server: http://10.0.0.30:5453
  bitwarden:
    enabled: true
    managed: false
    version: "2023.5.0"
  oh_my_posh:
    enabled: true
    managed: true
    version: latest
  zsh:
    enabled: true

machine:
  controlplane: false
  work: false

email: me@roxedus.dev
name: Roxedus

paths:
  XDG_CACHE_HOME: ".cache"
  XDG_CONFIG_HOME: ".config"
  XDG_DATA_HOME: ".local/share"
  XDG_STATE_HOME: ".local/state"
  ZDOTDIR: ".config/zsh"

git:
  sign: true
  format: ssh
  key: ""
  helper: cache
  store:
