integration:
  hishtory:
    enabled: true
    managed: true
    version: "0.208"
    settings:
      server: http://10.0.0.30:5453
  bitwarden:
    enabled: true
    managed: false
    version: "2023.5.0"
  oh_my_posh:
    enabled: true
    managed: true
    version: latest

email: me@roxedus.dev
name: Roxedus

git:
  sign: true
  format: ssh
  key: ""
  helper: cache
  store:
