codespaces: false

git:
  sign: true
  format: ssh
  key: ""
  helper: cache
  store:
  extend: false

integration:
  bitwarden:
    enabled: true
    managed: false
    version: "2023.5.0"
  eza:
    enabled: true
    managed: false
    version: latest
  hishtory:
    enabled: true
    managed: true
    version: "v0.208"
    offline: true
    settings:
      server: http://10.0.0.30:5453
  kubernetes:
    enabled: false
    managed: false
    version: "1.29.2"
  oh_my_posh:
    enabled: true
    managed: true
    version: latest
  podman:
    enabled: false
    managed: false
    version: latest
  tmux:
    enhanced: false
  zsh:
    enabled: true
    antidote: true
    omz: false

terminal:
  font: FiraCode
  size: 12
  theme: Nord
  alacritty:
    enabled: false
  windows:
    enabled: false
    profiles: []

machine:
  iac: false
  work: false
  ci: false
  wslName:

paths:
  XDG_CACHE_HOME: ".cache"
  XDG_CONFIG_HOME: ".config"
  XDG_DATA_HOME: ".local/share"
  XDG_STATE_HOME: ".local/state"
  ZDOTDIR: ".config/zsh"

user:
  email: me@roxedus.dev
  name: Roxedus
